import { GetStaticProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import { IBlogPostFields } from '../src/@types/contentful';
import ContentService from '../src/services/content';
import styles from '../styles/Home.module.css'
import safeStringify from "fast-safe-stringify"

interface HomeProps {
  posts: IBlogPostFields[];
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const articles = (
    await ContentService.instance.getEntriesByType<IBlogPostFields>("blogPost")
  ).map((entry) => entry.fields);
  const stringifiedData = safeStringify(articles);
  const posts = JSON.parse(stringifiedData);

  return {
    props: {
      posts,
    },
  };
};

export default function Home({ posts }: HomeProps) {
  console.log(posts)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {posts.map((article) => (
            <a key={article.slug} href={`/blog/${article.slug}`}>
              <h2>{article.title} &rarr;</h2>
              <p>{article.description}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
